name: Learning Github script

on:
  issues:
    types: [opened]
    
jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/github-script@0.8.0
      with: 
        github-token: ${{secrets.Github_token}}
        script: |
          github.issues.getComment({
            issue_number: context.issues.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: "🎉 You've created this issue comment using GitHub Script!!!
          })
